# For now we only use this configuration file to configure black & isort

[tool.black]
line-length = 100
target-version = ['py310']

exclude = '''
^/(
  (
      venv
    | tutorials/leveldb-bench/deps
    | plotbench/venv
  )/
  | plotbench/src/assets/defaultcustomsrc\.py
)
'''

[tool.isort]
profile = "black"
skip = [
    "tutorials/leveldb-bench/deps/",
    "plotbench/venv"
]
skip_glob = ["**/venv/**/*"]
